<?php
$cars = [
    [
        "id" => 0,
        "brand" => "Ford",
        "model" => "Focus",
        "modelYear" => 2004,
        "fuel" => "Benzina",
        "new" => true,
        "purchaseYear" => null,
        "distance" => null,
        "airConditioner" => true,
        "description" => "type text here",
        "warehouseNumber" => 1,
        "aviableForPurchase" => true,
        "price" => 20000
    ],
    [
        "id" => 1,
        "brand" => "Alpha Romeo",
        "model" => "Giulietta",
        "modelYear" => 2002,
        "fuel" => "Elettrica",
        "new" => false,
        "purchaseYear" => 2008,
        "distance" => 20000,
        "airConditioner" => false,
        "description" => "type text here",
        "warehouseNumber" => 3,
        "aviableForPurchase" => true,
        "price" => 2430
    ],
    [
        "id" => 2,
        "brand" => "FIAT",
        "model" => "500",
        "modelYear" => 2012,
        "fuel" => "Diesel",
        "new" => false,
        "purchaseYear" => 2018,
        "distance" => 1000,
        "airConditioner" => true,
        "description" => "type text here",
        "warehouseNumber" => 3,
        "aviableForPurchase" => true,
        "price" => 1200
    ],
    [
        "id" => 3,
        "brand" => "Alpha Romeo",
        "model" => "Brera",
        "modelYear" => 2010,
        "fuel" => "GPL",
        "new" => true,
        "purchaseYear" => null,
        "distance" => null,
        "airConditioner" => true,
        "description" => "type text here",
        "warehouseNumber" => 0,
        "aviableForPurchase" => false,
        "price" => 1500
    ],
    [
        "id" => 4,
        "brand" => "Renault",
        "model" => "Clio",
        "modelYear" => 1984,
        "fuel" => "Benzina",
        "new" => false,
        "purchaseYear" => 2000,
        "distance" => 8000000,
        "airConditioner" => false,
        "description" => "type text here",
        "warehouseNumber" => 1,
        "aviableForPurchase" => true,
        "price" => 100
    ],
    [
        "id" => 5,
        "brand" => "Ford",
        "model" => "Focus",
        "modelYear" => 2003,
        "fuel" => "Benzina",
        "new" => false,
        "purchaseYear" => 2001,
        "distance" => 23000,
        "airConditioner" => true,
        "description" => "type text her",
        "warehouseNumber" => 1,
        "aviableForPurchase" => true,
        "price" => 400
    ],
    [
        "id" => 6,
        "brand" => "Citroen",
        "model" => "C4",
        "modelYear" => 2004,
        "fuel" => "Diesel",
        "new" => false,
        "purchaseYear" => 2008,
        "distance" => 42000,
        "airConditioner" => true,
        "description" => "type text her",
        "warehouseNumber" => 1,
        "aviableForPurchase" => true,
        "price" => 5000
    ],
    [
        "id" => 7,
        "brand" => "FIAT",
        "model" => "Panda",
        "modelYear" => 2019,
        "fuel" => "Hybrid",
        "new" => true,
        "purchaseYear" => null,
        "distance" => null,
        "airConditioner" => true,
        "description" => "type text her",
        "warehouseNumber" => 3,
        "aviableForPurchase" => true,
        "price" => 22000
    ],
    [
        "id" => 8,
        "brand" => "Opel",
        "model" => "Corsa",
        "modelYear" => 2008,
        "fuel" => "Benzina",
        "new" => false,
        "purchaseYear" => 2008,
        "distance" => 400000,
        "airConditioner" => false,
        "description" => "type text her",
        "warehouseNumber" => 1,
        "aviableForPurchase" => true,
        "price" => 3400
    ],
];
